apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: session-gateway-ingress
  annotations:
    
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "local.gateway.com"
    http:
      paths:
      - path: /()(.*) 
        pathType: Prefix
        backend:
          service:
            name: gateway-service-http
            port:
              number: 80
